# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbot', '0002_user_symptoms_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symption', models.CharField(max_length=200)),
                ('current_lon', models.FloatField(default=0.0)),
                ('current_lat', models.FloatField(default=0.0)),
                ('symptom_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='current_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='symptom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbot.User'),
        ),
    ]
